version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: khalid
      POSTGRES_PASSWORD: khalid@123456
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:


